version: "3.9"

services:
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: climora-mosquitto
    ports:
      - "1883:1883"
    volumes:
      - mosquitto-data:/mosquitto/data
      - mosquitto-log:/mosquitto/log

  influxdb:
    extends:
      file: ./infrastructure/influxdb/docker-compose.influx.yml
      service: influxdb

  db_service:
    build:
      context: ./services/db_service
      dockerfile: Dockerfile
    container_name: climora-db-service
    depends_on:
      - influxdb
    env_file:
      - .env
      - ./infrastructure/influxdb/influxsecrets
    restart: unless-stopped
    ports:
      - "8002:8002"
    volumes:
      - ./shared:/app/shared

  data_collector:
    build:
      context: ./services/data_collector
      dockerfile: Dockerfile
    container_name: climora-data-collector
    depends_on:
      - mosquitto
      - db_service
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./shared:/app/shared  # wichtig, damit das geteilte Modell importiert werden kann


volumes:
  mosquitto-data:
  mosquitto-log:
  influxdb-data:
  influxdb-config:
