apiVersion: 1

datasources:
  - name: Climora InfluxDB
    type: influxdb
    access: proxy
    orgId: 1
    url: ${INFLUXDB_URL}
    basicAuth: false
    isDefault: true
    editable: false
    jsonData:
      version: Flux
      organization: ${INFLUXDB_ORG}
      defaultBucket: ${INFLUXDB_BUCKET}
      tlsSkipVerify: ${GRAFANA_INFLUX_TLS_SKIP_VERIFY}
    secureJsonData:
      token: ${INFLUXDB_API_TOKEN}
