FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . /app/db_service

ENV PYTHONPATH=/app

CMD ["uvicorn", "db_service.main:app", "--host", "0.0.0.0", "--port", "8002"]
